set(_CATKIN_CURRENT_PACKAGE "contest")
set(contest_VERSION "0.0.0")
set(contest_MAINTAINER "slam <slam@todo.todo>")
set(contest_PACKAGE_FORMAT "2")
set(contest_BUILD_DEPENDS "cv_bridge" "image_transport" "opencv2" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(contest_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "opencv" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(contest_BUILDTOOL_DEPENDS "catkin")
set(contest_BUILDTOOL_EXPORT_DEPENDS )
set(contest_EXEC_DEPENDS "cv_bridge" "image_transport" "opencv2" "roscpp" "sensor_msgs" "std_msgs" "tf")
set(contest_RUN_DEPENDS "cv_bridge" "image_transport" "opencv2" "roscpp" "sensor_msgs" "std_msgs" "tf" "opencv")
set(contest_TEST_DEPENDS )
set(contest_DOC_DEPENDS )
set(contest_URL_WEBSITE "")
set(contest_URL_BUGTRACKER "")
set(contest_URL_REPOSITORY "")
set(contest_DEPRECATED "")